os: osx
language: swift
osx_image: xcode10.1

xcode_project: NYPLAudiobookToolkit.xcodeproj
xcode_scheme: NYPLAudiobookToolkit
xcode_destination: platform=iOS Simulator,OS=11.4,name=iPhone X

cache:
  directories:
  - Carthage

before_install:
  - curl -L -O https://github.com/Carthage/Carthage/releases/download/0.25.0/Carthage.pkg
  - sudo installer -pkg Carthage.pkg -target /

before_script:
  - carthage update --platform iOS --cache-builds
